config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('users/', include('users.urls', namespace='users')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from shop.apps import ShopConfig
from shop.views import contacts, FlowersListView, FlowersDetailView, BlogCreateView, BlogListView, BlogDetailView, \
    BlogUpdateView, BlogDeleteView, toggle_activity, FlowersCreateView, FlowersUpdateView, FlowersDeleteView, \
    toggle_activity_fl, CategoryListView

app_name = ShopConfig.name

urlpatterns = [
    # path("", home, name='flowers_list.html'),
    path("", FlowersListView.as_view(), name='flowers_list/'),
    path("flowers/create", FlowersCreateView.as_view(), name='flowers_create/'),
    path("flowers/<int:pk>/detail/", FlowersDetailView.as_view(), name='flowers_detail/'),
    path("flowers/<int:pk>/update/", FlowersUpdateView.as_view(), name='flowers_update/'),
    path("flowers/<int:pk>/delete/", cache_page(60) (FlowersDeleteView.as_view()), name='flowers_delete/'),
    path("flowers/<int:pk>/activiti_fl/", toggle_activity_fl, name='toggle_activity_fl/'),

    path("flowers/category,", CategoryListView.as_view(), name='flowers_category/'),

    path("blog/create", BlogCreateView.as_view(), name='blog_create/'),
    path("blog/list/", BlogListView.as_view(), name='blog_list/'),
    path("blog/<int:pk>/detail/", BlogDetailView.as_view(), name='blog_detail/'),
    path("blog/<int:pk>/update/", BlogUpdateView.as_view(), name='blog_update/'),
    path("blog/<int:pk>/delete/", BlogDeleteView.as_view(), name='blog_delete/'),
    path("blog/<int:pk>/activiti/", toggle_activity, name='toggle_activity/'),



    path("contacts/", contacts, name='contacts.html'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_new_password, EmailConfirmationSentView, EmailConfirmedView, \
    EmailConfirmationFailedView, UserConfirmEmailView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login/'),
    path('logout/', LogoutView.as_view(), name='logout/'),
    path('register/', RegisterView.as_view(), name='register/'),
    path('profile/', ProfileView.as_view(), name='profile/'),
    path('profile/genpassword', generate_new_password, name='generate_new_password'),


    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent/'),
    path('confirm/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm'),
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed/'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed/'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from shop.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=100, verbose_name='страна', **NULLABLE)
    verification_key = models.CharField(max_length=6, verbose_name='ключ', **NULLABLE)
    is_verified = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.email}'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from shop.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', "password1", 'password2', 'phone', 'country', 'avatar')


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'country', 'avatar')

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)

            self.fields['password'].widget = forms.HiddenInput()


class UserKeyForm(StyleFormMixin, forms.Form):
    verification_key = forms.CharField(max_length=6, label='ключ')

users/views.py
from django import forms
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.sites.models import Site
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views import View
from django.views.generic import CreateView, UpdateView, TemplateView

from config import settings
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class UserIsNotAuthenticated(UserPassesTestMixin):

    def test_func(self):
        if self.request.user.is_authenticated:
            messages.info(self.request, 'Вы уже авторизованы. Вы не можете посетить эту страницу.')
            raise PermissionDenied
        return True

    def handle_no_permission(self):
        return redirect('shop:flowers_list')


class LoginUser(SuccessMessageMixin, LoginView):
    template_name = 'user/login.html'
    success_message = 'Добро пожаловать на сайт!'

    def get_success_url(self):
        return reverse_lazy('shop:flowers_list')


class RegisterView(UserIsNotAuthenticated, CreateView):
    """
    Регистрация на сайте
    """
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('shop:flowers_list')
    template_name = 'users/register.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация на сайте'
        return context

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy('users:confirm', kwargs={'uidb64': uid, 'token': token})
        current_site = Site.objects.get_current().domain

        send_mail(
            subject='Подтвердите свой электронный адрес',
            message=f'Пожалуйста, перейдите по следующей ссылке, чтобы подтвердить свой адрес электронной почты: http://{current_site}{activation_url}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email],
            fail_silently=False,
        )

        return redirect('users:email_confirmation_sent/')


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('shop:flowers_list/')

    def get_object(self, queryset=None):
        return self.request.user


def generate_new_password(request):
    new_password = User.objects.make_random_password(length=10,
                                                     allowed_chars='abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789')

    send_mail(
        subject='вы сменили пароль',
        message=f'Ваш новый пароль:{new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email],

    )

    request.user.set_password(new_password)
    request.user.save()

    return redirect(reverse('shop:flowers_list/'))


class UserConfirmEmailView(View):
    def get(self, request, uidb64, token):
        uid = urlsafe_base64_decode(uidb64)
        user = User.objects.get(pk=uid)

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('users:email_confirmed/')
        else:
            return redirect('users:email_confirmation_failed/')


class EmailConfirmationSentView(TemplateView):
    template_name = 'users/email_confirmation_sent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Письмо активации отправлено'
        return context


class EmailConfirmedView(TemplateView):
    template_name = 'users/email_confirmed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес активирован'
        return context


class EmailConfirmationFailedView(TemplateView):
    template_name = 'users/email_confirmation_failed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес не активирован'
        return context

users/templates/users/confirm_email.html
{% extends 'shop/base.html' %}
{% block content %}

{% endblock %}

users/templates/users/email_confirmation_failed.html
{% extends 'shop/base.html' %}

{% block content %}
<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Ошибка подтверждения по электронной почте</h4>
    <p>Ссылка для подтверждения по электронной почте недействительна или срок ее действия истек.
        Пожалуйста, зарегистрируйтесь снова.</p>
</div>
{% endblock %}

users/templates/users/email_confirmation_sent.html
{% extends 'shop/base.html' %}

{% block content %}
<div class="alert alert-info" role="alert">
    <h4 class="alert-heading">Письмо подтверждения отправлено!</h4>
    <p>
        На ваш адрес электронной почты было отправлено письмо с подтверждением.
        Пожалуйста, проверьте свою электронную почту и нажмите на ссылку подтверждения, чтобы завершить регистрацию.
        Если письмо не пришло, проверьте папку спам.
    </p>
</div>
{% endblock %}

users/templates/users/email_confirmed.html
{% extends 'shop/base.html' %}

{% block content %}
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Электронная почта подтверждена</h4>
    <p>Ваш адрес электронной почты успешно подтвержден. Спасибо за регистрацию!</p>
</div>
{% endblock %}

users/templates/users/key_verification.html
{% extends 'shop/base.html' %}
{% block content %}

<form class="row" method="post" enctype="multipart/form-data">
    <div class="col-4"></div>
    <div class="col-4 mb-4">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">
                    Верификация
                </h4>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-success">проверить</button>
            </div>
        </div>

    </div>
    </div>
</form>

{% endblock %}

users/templates/users/login.html
{% extends 'shop/base.html' %}
{% block content %}

<form class="row" method="post" enctype="multipart/form-data">
    <div class="col-4"></div>
    <div class="col-4 mb-4">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">
                    Вход
                </h4>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-success">Войти</button>
            </div>
        </div>

    </div>
    </div>
</form>

{% endblock %}tml>

users/templates/users/register.html
{% extends 'shop/base.html' %}
{% block content %}

<form class="row" method="post" enctype="multipart/form-data">
    <div class="col-4"></div>
        <div class="col-4 mb-4">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">
                        Регистрация
                    </h4>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </div>
                <div class="card-footer">
<!--                    <a href="#" class="btn btn-danger">Сгенерировать ключ</a>-->
                </div>
            </div>

        </div>
    </div>
</form>

{% endblock %}

users/templates/users/user_form.html
{% extends 'shop/base.html' %}
{% block content %}

<form class="row" method="post" enctype="multipart/form-data">
    <div class="col-4"></div>
        <div class="col-4 mb-4">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">
                        Профиль
                    </h4>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
                <div class="card-footer">
                    <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Сгенерировать пароль</a>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock %}